UrlShortner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('url.urls'))
]

poll/urls.py
from django.urls import path
from .views import home_view, create_view, vote_view, results_view, delete_view

urlpatterns = [
    path('', home_view , name = 'home'),
    path('create',create_view, name = 'create'),
    path('vote/<poll_id>',vote_view, name = 'vote'),
    path('create/<poll_id>',results_view, name = 'results'),
    path('delete/<poll_id>',delete_view, name = 'delete'),
]

pollproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('poll.urls'))
]

url/urls.py
from django.contrib import admin
from django.urls import path
from  .views import home_view, URLRedirector, db_view, login_view,register_view, logout_view, delete_view
app_name = 'url'
urlpatterns = [
    path('', home_view,name='home'),
    path('<url>/',URLRedirector,name='redirector'),
    path('db',db_view, name = 'database'),
    path('login',login_view, name = 'login'),
    path('register',register_view, name='register'),
    path('logout',logout_view, name='logout'),
    path('delete/<id>',delete_view, name ='delete')
]

poll/models.py
from django.db import models

# Create your models here.
class Poll(models.Model):
    question = models.TextField()
    option1 = models.CharField(max_length = 30)
    option2 = models.CharField(max_length = 30)
    option3 = models.CharField(max_length = 30)
    option1count = models.IntegerField(default=0)
    option2count = models.IntegerField(default=0)
    option3count = models.IntegerField(default=0)

url/models.py
from django.db import models

# Create your models here.
class Url(models.Model):
    """Model definition for Url."""
    actual_url = models.CharField(max_length=220)
    shortcode = models.CharField(max_length = 15,null=True, blank = True)

poll/forms.py
from django import forms
from .models import Poll

class CreatePollForm(forms.ModelForm):
    """Form definition for CreatePoll."""

    class Meta:
        """Meta definition for CreatePollform."""

        model = Poll
        fields = ('question','option1','option2','option3')

url/forms.py
from django import forms
from .models import Url
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from .utils import create_shortcode

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUrlForm(forms.ModelForm):
    """Form definition for CreateUrl."""
    class Meta:
        """Meta definition for CreateUrlform."""

        model = Url
        fields = ('actual_url','shortcode')

    def clean_actual_url(self):
        # print('I am validating URL')
        url_v = self.cleaned_data['actual_url']
        # print('url_v: ' + str(url_v))
        try:
            validate = URLValidator(
                    schemes=("http", "https", "ftp", "ftps", "rtsp", "rtmp")
                )
            validate(url_v)
        except:
            # print('Invalid URL')
            raise ValidationError('Enter correct URL')
        return url_v
        
    def clean_shortcode(self):
        # print('I am here to validate shortcode')
        sc = self.cleaned_data['shortcode']
        if sc == None:
            sc = create_shortcode()
        if len(sc)<5 or len(sc)>15:
            raise ValidationError('Minimum and Maximum shortcode length can be 5 and 15 respectively')
        if Url.objects.filter(shortcode=sc).exists():
            raise ValidationError('Cannot process this code, enter another unique code')
        return sc

class CreateUserForm(UserCreationForm):
    class meta:
        model = User
        fields = ['username','password1','password2']

poll/views.py
from django.shortcuts import render, redirect
from .forms import CreatePollForm
from .models import Poll
from django.http import HttpResponse

# Create your views here.
def home_view(request, *args, **kwargs):
    polls = Poll.objects.all()
    context = {'polls' : polls}
    return render(request,'poll/home.html',context)

def create_view(request, *args, **kwargs):
    if request.method=="POST":
        form = CreatePollForm(request.POST)
        if form.is_valid:
            form.save()
            print('form saved')
            return redirect('home')
        else:
            print("FOrm Failed")
    else:
        form = CreatePollForm()
        context = {'form' : form}
        return render(request,'poll/create.html',context)

def vote_view(request, poll_id,*args, **kwargs):
    poll_instance = Poll.objects.get(pk=poll_id)
    if request.method == "POST":
        selected_option = request.POST['poll']
        if selected_option=='option1':
            poll_instance.option1count+=1
        elif selected_option=='option2':
            poll_instance.option2count+=1
        elif selected_option=='option3':
            poll_instance.option3count+=1
        else:
            return HttpResponse(400, "Invalid Form")
        poll_instance.save()
        print('saved')
        return redirect('home')

    context = {'poll_instance' : poll_instance}
    return render(request,'poll/vote.html',context)

def results_view(request, poll_id,*args, **kwargs):
    poll_instance = Poll.objects.get(pk=poll_id)
    context = {'poll_instance' : poll_instance}
    return render(request,'poll/results.html',context)
    
def delete_view(request,poll_id,*args,**kwargs):
    poll_instance = Poll.objects.get(pk=poll_id)
    poll_instance.delete()
    return redirect('home')

url/views.py
from django.shortcuts import render, redirect
from .forms import CreateUrlForm, CreateUserForm
from django.urls import reverse
from . import models
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def home_view(request):
    form = CreateUrlForm(request.POST or None)
    code_string = ''
    shortcode = ''
    if request.method == "POST":
        form = CreateUrlForm(request.POST)
        if form.is_valid():

            ac_url = form.cleaned_data.get('actual_url')            
            code_string = form.cleaned_data.get('shortcode')
            shortcode = code_string
            # print('I will try to print path')
            # code_string =  request.build_absolute_uri(reverse('url.home')) +  code_string
            # print(code_string)
            # print('code string was not null')
            if models.Url.objects.filter(actual_url = ac_url).exists():
                prev_obj = models.Url.objects.get(actual_url=ac_url)
                shortcode = prev_obj.shortcode
                print("YES it exists " + shortcode)
            else:
                form.save()
            # form = CreateUrlForm()

    context = {'form': form, 'shortcode':shortcode,}
    return render(request,'home.html',context)

def URLRedirector(request, url):
    url_qs = models.Url.objects.get(shortcode=url)
    real_link = url_qs.actual_url
    print(real_link)
    return redirect(real_link)

def db_view(request):
    objects = models.Url.objects.all()
    context = {'objects' : objects}
    return render(request, 'database.html',context)


def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        print('Username: ' + str(username))
        print('Password: ' + str(password))
        user = authenticate(request,username = username, password = password)
        if user is not None:
            login(request, user)
            return redirect('url:home')
        else:
            messages.add_message(request, messages.INFO, 'Invalid Credentials')
    context = {}
    return render(request, 'login.html',context)

def register_view(request):
    form = CreateUserForm(request.POST or None)
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('url:login')
    context = {'form' : form}
    return render(request, 'register.html',context)

def logout_view(request,*args,**kwargs):
    logout(request)
    return redirect('url:home')

def delete_view(request, id):
    obj = models.Url.objects.get(pk=id)
    obj.delete()
    return redirect('url:database')

poll/templates/poll/base.html
{% load static %}


<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Arvo:700&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:900&display=swap" rel="stylesheet"> 

    <link rel="stylesheet" type = "text/css" href="{% static 'main.css' %}" />

    <title>{% block title %}{% endblock %}</title>
  </head>


  
  <body>

    <div class="jumbotron jumbotron-custom">
      <h1 class = "display-3 text-center">Poll your voice</h1>
    </div>

    <!-- navbar -->
    <navbar class="navbar navbar-expand-sm bg-dark navbar-dark">
      <div class="container-fluid">
        <div class="navbar-brand">
          <img src="{% static 'logo.jpg' %}" height="50px" width="50px" alt="Poll">
        </div>
        <span class="navbar-text px-3">
          <h1 class="text-white">Poll</h1>
        </span>
        <button class="navbar-toggler custom-toggler" data-toggle = "collapse" data-target = "#navbar_items">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse text-center" id = "navbar_items">

          <ul class="nav navbar-nav">
            <li class="nav-item">
              <a href="{% url 'home' %}" class="nav-link text-white">Home</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'create' %}" class="nav-link text-white">Create</a>
            </li>
          </ul>
        </div>
      </div>
    </navbar>

    {% block body %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

poll/templates/poll/create.html
{% extends 'poll/base.html' %}
{% load widget_tweaks %}

{% block title %}New Poll{% endblock %}

{% block body %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-10 my-3">
            <div class="card card-header"style="background: #91818a;">
                <h1 class="display-5 text-center">Create a new Poll</h1>
            </div>
                <div class="card card-body create-poll-custom mx-auto">
                    <!-- <div class="card-title text-center text-white">
                        <h2 class="text-capitalize">Create a new Poll</h2> -->
                        <h3>Enter Question</h3>
                        <form method="POST"> {% csrf_token %}
                            <!-- question -->
                            <div class="form-group mt-1"> 
                                {% render_field form.question class="form-control" rows="3" %}
                                <!-- <textarea name="question" id="question" rows="3" class="form-control"></textarea> -->
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <span>option A</span>
                                    {% render_field form.option1 class="form-control form-control-lg" %}
                                    <!-- <input type="text" id="question" class="form-control form-control-lg"> -->
                                </div>
                                <div class="col-md-4">
                                    <span>option B</span>
                                    {% render_field form.option2 class="form-control form-control-lg" %}
                                    <!-- <input type="text" id="question" class="form-control form-control-lg"> -->
                                </div>
                                <div class="col-md-4">
                                    <span>option C</span>
                                    {% render_field form.option3 class="form-control form-control-lg" %}
                                    <!-- <input type="text" id="question" class="form-control form-control-lg"> -->
                                </div>
                            </div>
                            
                            <div class="row justify-content-center">
                                <button type="submit" class=" btn btn-warning btn-lg text-uppercase mt-4">submit</button>
                            </div>
                        </form>
                    </div>
                </div>
        </div>
    </div>
</div>
{% endblock %}

poll/templates/poll/home.html
{% extends 'poll/base.html' %}

{% block title %}Homepage{% endblock %}

{% block body %}


<section class="py-5">
    <div class="container mx-auto">
        <div class="row">
            <div class="col-lg-10">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title text-capitalize text-center">available polls</h3>
                    </div>
                </div>
                <br>
                {% for poll in polls %}
                <ui class="list-group">
                    <li class="list-group-item align-middle">
                        <strong>{{ poll.question }}</strong>
                        <span class="float-right">
                            <a href="{% url 'vote'  poll.id %}" class="btn btn-xs btn-info">Vote</a>&nbsp; &nbsp;
                            <a href="{% url 'results' poll.id %}" class="btn btn-xs btn-warning">Results</a>&nbsp;
                            <a href="{% url 'delete' poll.id %}" class="btn btn-xs btn-primary">Delete</a>&nbsp;
                        </span>
                    </li>
                    
                </ui>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

poll/templates/poll/results.html
{% extends 'poll/base.html' %}

{% block title %}Results!{% endblock %}

{% block body %}

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-10 my-3">
            <div class="card card-header"style="background: #91818a;">
                <h1 class="display-5 text-center">Results</h1>
            </div>
                <div class="card card-body create-poll-custom mx-auto">
                    <h4>{{ poll_instance.question }}</h4>
                    <hr>
                    <div class="list-group">
                        <div class="list-group-item list-item-custom">
                            <h6>{{ poll_instance.option1 }} --- {{ poll_instance.option1count }}</h6>
                        </div>
                        <div class="list-group-item list-item-custom">
                            <h6>{{ poll_instance.option2 }} --- {{ poll_instance.option2count }}</h6>
                        </div>
                        <div class="list-group-item list-item-custom">
                            <h6>{{ poll_instance.option3 }} --- {{ poll_instance.option3count }}</h6>
                        </div>
                    </div>
                </div>
        </div>
    </div>
</div>

{% endblock %}

poll/templates/poll/vote.html
{% extends 'poll/base.html' %}

{% block title %}Vote!{% endblock %}

{% block body %}

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-10 my-3">
            <div class="card card-header"style="background: #91818a;">
                <h1 class="display-5 text-center">Cast your vote</h1>
            </div>
                <div class="card card-body create-poll-custom mx-auto">
                    <h4>{{poll_instance.question}}</h4>
                    <hr>
                    <form method="POST"> {% csrf_token %}
                       <div class="btn-block form-group" data-toggle="buttons">
                           <div class="row py-3">
                               <div class="col-md-4 d-flex justify-content-center">
                                    <label class="btn active">
                                        <span class="d-flex">
                                            <input type="radio" name="poll" value="option1" autocomplete="off" checked>&nbsp;
                                            {{ poll_instance.option1 }}
                                        </span>
                                    </label>
                               </div>
                               <div class="col-md-4 d-flex justify-content-center">
                                    <label class="btn">
                                        <span class="d-flex">
                                            <input type="radio" name="poll" value="option2" autocomplete="off">&nbsp;
                                            {{ poll_instance.option2 }}
                                        </span>
                                    </label>
                               </div>
                               <div class="col-md-4 d-flex justify-content-center">
                                <label class="btn">
                                    <span class="d-flex">
                                        <input type="radio" name="poll" value="option3" autocomplete="off ">&nbsp;
                                        {{ poll_instance.option3 }}
                                    </span>
                                </label>
                           </div>
                        </div>
                        <div class="row justify-content-center mt-1">
                            <button type="submit" class="btn btn-warning btn-lg">submit</button>
                        </div>
                    </form>
                </div>
        </div>
    </div>
</div>

{% endblock %}

url/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/0b22eaefe2.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'main.css' %}">
  <title>{% block title %}{% endblock %}</title>
</head>

<body>


  <!-- navbar -->
  <nav class="navbar navbar-expand-sm navbar-dark custom-nav">
    <div class="container">
      <div class="navbar-brand">
        <h4 class="text-lead my-auto">Easy-URL</h4>
      </div>
      <button type="button" class="navbar-toggler custom-toggler" data-toggle="collapse" data-target="#navbar_items">
        <i class="fas fa-bars text-white"></i>
        <!-- <span class="navbar-toggler-icon"></span> -->
      </button>
      <div class="collapse navbar-collapse text-center" id="navbar_items">
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <a href="{% url 'url:home' %}" class="nav-link text-white">Home</a>
          </li>
        </ul>

        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
            <a href="{% url 'url:database' %}" class="nav-link text-white">View URL's</a>
          </li>
          <li class="nav-item">
            {% if request.user.is_authenticated %}
            <a href="{% url 'url:logout' %}" class="nav-link text-white">Logout</a>
            {% else %}
            <a href="{% url 'url:login' %}" class="nav-link text-white">Login</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>



  {% block body %}{% endblock %}
  <!-- Footer -->
  <footer class="footer mt-auto">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 footer-copyright text-center">
          &copy; slayer-easy-url
        </div>
      </div>
    </div>
  </footer>





  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" crossorigin="anonymous"></script> -->
</body>

</html>

url/templates/database.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Database{% endblock %}
{% block body %}


<section id="database_filler" class="bg-dark">
    <div class="container py-5">
        <div class="row">
            <div class="col text-white text-center text-capitalize">
                <h4 class="font-weight-bold">This page contains all shortened URL's</h4>
            </div>
        </div>
    </div>
</section>

<div class="container py-5">
    <div class="row py-3">
        {% for obj in objects %}
        <div class="col-md-6 col-lg-4 py-3">
            <div class="card card-header">
                <div class="card-title text-center font-weight-bold">
                    {{obj.actual_url}}
                </div>
            </div>
            <div class="card">
                <div class="list-group">
                    <li class="list-group-item text-center">
                        <a href="{% url 'url:redirector' obj.shortcode %}">{{ request.get_host }}/{{obj.shortcode}}</a>
                    </li>
                </div>
            </div>
            {% if request.user.is_authenticated %}
            <div class="card card-footer">
                <a href="{% url 'url:delete' obj.id %}" class="btn btn-danger text-capitalize">Delete</a>
            </div>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

url/templates/home.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Home{% endblock %}

{% block body %}


<section id="welcome">
    <div class="container-fluid py-5">
        <div class="row height align-items-center">
            <div class="col text-center text-white">
                <h1 class="font-weight-bold">Welcome to URL shortener</h1>
                <p class="lead text-white">Shorten your url's in an easy way!</p>
            </div>
        </div>
    </div>
</section>


<section id="shrink-url">
    <div class="container">
        <div class="row">
            <div class="col my-5 card card-body">
                <form method="POST"> {% csrf_token %}
                    <div class="form-group mt-3">
                        <!-- <input type="text" name="url" class="form-control form-control-lg" placeholder="Enter your URL here"> -->
                        {% render_field form.actual_url name='url' class="form-control form-control-lg" placeholder="Enter your URL here" %}
                    </div>
                    {{form.actual_url.errors }}
                    <div class="form-group mt-3">
                        <!-- <input type="text" name="shortcode" class="form-control form-control-lg" placeholder="Enter shortcode (optional)"> -->
                        {% render_field form.shortcode name='shortcode' class="form-control form-control-lg" placeholder="Enter shortcode (optional)" %}
                    </div>
                    {{form.shortcode.errors }}
                    <div class="row justify-content-center">
                        <button type="submit" class="btn btn-info btn-lg">Generate</button>
                    </div>
                    <div class="input-group my-5">
                        <div class="input-group-prepend">
                            <span class="input-group-text">shrinked-url:</span>
                        </div>
                        <!-- <input type="text" name="shrinked-url" readonly class="form-control form-control-lg" value="{{code_string}}" > -->
                        <div class="form-control form-control-lg scrolling-wrapper" type='text'>
                            {% if shortcode != '' %}
                            <!-- { request.get_host }}/{{shortcode}} -->
                            <a href="{% url 'url:redirector' shortcode %}"><small>{{ request.get_host }}/{{shortcode}}</small></a>
                            {% endif %}
                        </div>
                        <a href="{% url 'url:home' %}" class="input-group-append"><button class="btn btn-primary"
                                type="button" value="reset">New URL</button></a>
                        <!-- <div class="input-group-append">
                            <input type="reset" value = "New URL">
                        </div> -->
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

url/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Login!{% endblock %}
{% block body %}

{% include 'navbar.html' %}

<section id="contact" class="py-5">
    <div class="container">
        <!-- title -->
        <div class="row">
            <div class="col text-center mx-auto">
                <h1 class="display-4 text-uppercase text-dark mb-0">
                    <strong class = "font-weight-bold">Welcome</strong>
                </h1>
                <div class="bg-warning title-underline"></div>
            </div>
        </div>
        <!-- end of title -->
        <div class="row py-3">
            <div class="col-md-6 my-3 mx-auto">
                <div class="card card-body create-poll-custom mb-0">
                    <form method="POST"> {% csrf_token %}
                        <!-- name -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" name = "username" class="form-control" placeholder="username">
                        </div>
                        <!-- end of name -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input type="password" name = "password" class="form-control" placeholder="password">
                        </div>
                        {% if messages %}
                        <ul>
                        {% for message in messages %}
                        <li class="{{messgae.tags}}">{{message}}</li>
                        {% endfor %}
                        </ul>
                        {% endif %}
                        <div class="row justify-content-center mt-1">
                            <button type="submit" class="btn btn-warning btn-lg text-uppercase">Login</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center">
                    <a href="{% url 'url:register' %}"> Not registered yet? Click here to register!</a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

url/templates/navbar.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<nav class="navbar navbar-expand-sm navbar-dark custom-nav">
    <div class="container">
        <div class="navbar-brand">
            <h4 class="text-lead my-auto">Easy-URL</h4>
        </div>
        <button type="button" class="navbar-toggler custom-toggler" data-toggle = "collapse" data-target = "#navbar_items">
            <!-- <i class="fas fa-bars text-white"></i> -->
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id = "navbar_items">

            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a href="{% url 'url:home' %}" class="nav-link text-white">Home</a>
              </li>
            </ul>
  
            <ul class="nav navbar-nav ml-auto">
            <li class="nav-item">
                <a href="{% url 'url:database' %}" class="nav-link text-white">View URL's</a>
            </li>
              <li class = "nav-item">
                {% if request.user.is_authenticated %}
                <a href="{% url 'url:logout' %}" class="nav-link text-white">Logout</a>
                {% else %}
                <a href="{% url 'url:login' %}" class="nav-link text-white">Login</a>
                {% endif %}
              </li>
            </ul>
          </div>
        </div>
    </div>
</nav>
{% endblock %}